INSERT INTO COIN_INVENTORY(COIN_VAL, COIN_COUNT) VALUES (0.01, 100);
INSERT INTO COIN_INVENTORY(COIN_VAL, COIN_COUNT) VALUES (0.05, 100);
INSERT INTO COIN_INVENTORY(COIN_VAL, COIN_COUNT) VALUES (0.10, 100);
INSERT INTO COIN_INVENTORY(COIN_VAL, COIN_COUNT) VALUES (0.25, 100);